### ISSUE TITLE
Create a pykern testing wiki with emphasis on file_eq

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#189] opened 2022-06-02 17:21 UTC

**Comment by gurhar1133** [comment] 2022-06-02 17:35
Should I go over data_dir() and work_dir() usage with file_eq()?

**Comment by robnagler** [comment] 2022-06-02 17:40
Yes, that would be great. Also that imports are in the functions, not the top level.

One thing we should resolve is whether we should unqualified imports:

```py
def test_case():
    import pykern.pkunit
```

or

```py
    from pykern import pkunit
```

or 

```py
    from pykern.pkunit import file_eq
```

**Comment by gurhar1133** [comment] 2022-06-02 17:57
> Yes, that would be great. Also that imports are in the functions, not the top level.
> 
> One thing we should resolve is whether we should unqualified imports:
> 
> ```python
> def test_case():
>     import pykern.pkunit
> ```
> 
> or
> 
> ```python
>     from pykern import pkunit
> ```
> 
> or
> 
> ```python
>     from pykern.pkunit import file_eq
> ```

I thought we did unqualified (like the last one) in function definitions. Is this correct @e-carlin ?

**Comment by robnagler** [comment] 2022-06-03 13:40
So:

* fully qualified imports at module level
* module level imports at the function level
* PKDict, pkdp, pkdlog, pkdc, etc. are exceptions

Yes, we would alias 
```py
pkok = ok
```

**Comment by robnagler** [comment] 2022-06-03 20:28
@mkeilman please review https://github.com/radiasoft/pykern/wiki/Testing

**Comment by mkeilman** [comment] 2022-06-06 19:49
Suggestions follow - I'll put them in separate comments

> Pykern provides a <s>testing</s> framework built on top of [pytest](http://docs.pytest.org/) to eliminate much of the boilerplate in testing. <s>This allows you to write simple tests.</s>

**Comment by mkeilman** [comment] 2022-06-06 20:40
> <s>You run</s> **Run** the test with:

> <s>If you want</s> To run a specific test case: <s>then you can use</s>

(might continue the example here, along the lines of "Following the example, ```pykern test foo_test.py```...")

> <s>You can also just invoke pykern test if there is a tests/ sub directory within the directory you invoke pykern in, or if you are in that tests/ directory</s> **To run tests in all the ?appropriate? files under ```.``` or ```./tests```:**

```
pykern test
```

I think test files have to be named ```<xyz>_test.py``` in order for ```pykern test``` to find them, correct? Inform the reader of that

**Comment by mkeilman** [comment] 2022-06-06 20:48
> <s>Even though pykern test is built on top of pytest, you'll want to get used to using pykern test rather than just pytest ..., because it sets up the configuration environment properly, which you'll need for more complex tests.</s> Note also that if you are using Bivio's emacs macros, you can run the test with \C-c \C-m.)

Not sure we need the first part since the reader is here, after all. If there is a link to those bivio macros, include it. But does one expect the reader to know what bivio even is?

**Comment by gurhar1133** [comment] 2022-06-06 20:55
Thanks @mkeilman 👍

**Comment by mkeilman** [comment] 2022-06-06 21:04
> Raises ```PKFail``` <s>exception</s>, with *args or **kwargs passed to fmt.format(*args, **kwargs) as **its** message. ```PKFail``` is **a** subclass of ```AssertionError```.

I think any refs to classes, methods, or the like should be in ```code format```.  Should we explain why one might use this "test" (since it just fails)?

**Comment by mkeilman** [comment] 2022-06-06 21:14
> <s>Raises</s> **Calls** ```pkfail()``` if ```expect``` != ```actual```

Or maybe just "fails  if ```expect``` != ```actual``` "?

**Comment by gurhar1133** [comment] 2022-06-06 21:35
Made changes based on your suggestions @mkeilman LMK if anything else.

**Comment by mkeilman** [comment] 2022-06-06 22:00
> ```with pkunit.pkexcept(<exception class or regular expression>, <fmt_str>): <code that may trigger exception>```

"code that **should** trigger the given exception"

> <s>Expect an exception to be thrown and match or output msg</s> **If the argument is an exception class, passes when the code raises that exception; fails otherwise. If the argument is a regex, passes when the code raises any exception whose message matches that regex; fails otherwise.**

(if I am interpreting this correctly)

> <s>i.e.</s> Code <s>in the</s> **under** ```with pkunit.pkexcept()``` <s>block</s> will not trigger exception of class 
\<exception class\>

In the regex example, you might make the regex more more obviously that (```r'^missing'``` ?)

**Comment by mkeilman** [comment] 2022-06-07 00:55
> ```pkunit.pkok(condition)```

"Expression"?

> <s>If condition is not true, throw PKFail with calling context</s> **Passes if ```expression``` is truthy; fails otherwise**

**Comment by mkeilman** [comment] 2022-06-07 01:07
> pkre

For consistency add the usage
```
pkunit.pkre(regex, actual)
```
**Passes if ```actual``` matches ```regex``` via ```re.search()```; fails otherwise**

> This example from sirepo/tests/uri_router_test.py compares a uri value with a regex to make sure the uri **has**  the correct format

> ```pkunit.pkre('http://[^/]+/en$', uri)```

**Comment by mkeilman** [comment] 2022-06-07 02:45
> <s>It's nice to have a directory full of</s> **It can be useful to keep** files that will be useful for a particular test **in a single directory**.  ```data_dir()``` <s>computes the</s>  **accesses files in** a data directory based on the test name.

When using code format, add parens to method names so readers can distinguish them from variables and parameters at a glance.

> <s>This example highlights the usefulness of not having to manage directory structure when writing tests.</s> **For example, if the file ```setup_test.py``` contains**

```
def test_example():
   f = data_dir('test_file.txt')
   text = pkio.read_text(f)
   actual = foo()
   pkunit.pkeq(text, actual)
```

> <s>We just have to know what the name of the file in data_dir is and we can easily get the path to it</s> ```f``` would point to ```setup_data/test_file.txt```.

**Comment by mkeilman** [comment] 2022-06-07 02:58
> <s>It's</s> Also useful <s>to have</s> **is** a temporary directory for the output  of <s>your</s> test functions.

Add period

> ```work_dir()``` returns an ephemeral work directory, <s>like data_dir, and creates</s> **creating** it if necessary, **using the same rules as ```data_dir()```. To continue the previous example, ```work_dir()``` in the file ```setup_test.py``` would create and reference ```setup_work/```**

**Comment by mkeilman** [comment] 2022-06-07 15:12
> <s>Removes</s> **If the directory defined in ```work_dir()``` exists, this removes it and its contents**, recreates it,<s> All contents of the test directory will be removed.</s> **and returns the path** <s>the new empty work directory.</s>

**Comment by mkeilman** [comment] 2022-06-07 21:39
> ```file_eq()``` is a flexible <s>pkunit</s> file comparison function.

> The handle for ```file_eq()``` is:

> **It takes a path to a file in the work directory and either a positional argument specifying content for comparison, a keyword argument ```actual``` specifying the same content, or a keyword argument ```actual_path``` specifying the path to a file for comparison. The three options are mutually exclusive.  If ```file_eq()``` fails, it will output a ```diff``` to help pinpoint the discrepancies.**

I think that  encapsulates things and the next sentences can be omitted.

> <s>actual will be set by args[0]. But if *args are not specified then actual will be determined by actual_path keyword argument, or by you setting actual as a keyword arg.</s>

> <s>Note: you may only specify one or no positional args. This is because you can only provide one actual. Also, you may not provide both a positional actual and a keyword arg actual.</s>

> <s>So you can provide actual as a positional arg, or as a keyword arg, or you can specify the actual_path as a keyword argument. This gives the user quite a bit of flexibility.</s>

> <s>expect_path</s> ```file_eq()``` can <s>take</s> **compare** .txt, .csv., jinja, or .json <s>just plain text</s> files, **and, if the [```pandas```](https://pandas.pydata.org/) package is installed, .xlsx files.**<s>actual can be all of the same as expect_path or even .xlsx which is then converted to .csv to be compared with expect_path.Note that if you want to automatically compare xlsx files, you need to install pandas.</s> 

Save the xlsx details for an example.

> <s>If expect_path ends in</s> **When comparing a .json file to content specified by ```actual```**, <s>in a file and actual_path does not exist,</s> ```file_eq()``` uses  [```pkjson```](https://github.com/radiasoft/pykern/blob/master/pykern/pkjson.py)  <s>will be used</s> to load **and parse** <s>expect_path</s> **the file to make the comparison, and to write the contents of ```actual``` to a file in ```work_dir()```.** <s>and a data structure comparison will be used with actual and actual_path will be written. This allows easy testing of complex results.</s>

> <s>If expect_path ends with</s> **When comparing .jinja,  ```file_eq()``` renders it with  [pykern.pkjina.render_file](https://github.com/radiasoft/pykern/blob/723ac21cbb56ed3afd08afc6b5354666cae0d766/pykern/pkjinja.py#L19) using a jinja context supplied by the ```j2_ctx``` keyword argument.** <s>it will be rendered with pykern.pkjina.render_file, and you must supply j2_ctx in kwargs</s>

There are a lot of options listed so I think an example for each one would be helpful, including the complicated xlsx stuff.

> <s>… operations that establish actual_path contents and set actual_path to variable `a` set to actual_path</s>

```
file_eq('expected_results.txt', actual_path='actual_results.txt')
```

Even though one can use the ```expect_path``` keyword, we don't mention it earlier. Use a string literal for ```actual_path```.  Also start with basic text comparison and move to the more complicated examples.

> If <s>you use</s> ```file_eq()``` **fails and the diff includes** a ```No newline at end of file``` message for both ```expect``` and ```actual```, **it** can be ignored. However, there may be other **differences** <s>between expect and actual</s>, so carefully check the result of the test.

**Comment by gurhar1133** [comment] 2022-06-08 22:06
Made some more edits @mkeilman LMK what you think

**Comment by mkeilman** [comment] 2022-06-09 19:10
That looks good. I still think this:

> Excel spreadsheets are supported. If you want to automatically compare xlsx files, you need to install pandas, which will be used to convert Excel files as follows. If the name of the expect (out) file is foo.csv, then the first sheet (sheet 0) in the corresponding work_dir xlsx will be converted to foo.csv before comparison. If the expect (out) file has a #<digit>, e.g. foo#3.csv, then the fourth sheet will be extracted from the actual xlsx to foo#3.csv in the work_dir.

should move to the corresponding ```file_eq``` example. It's not specific to ```case_dirs```.

**Comment by gurhar1133** [comment] 2022-06-09 19:23
@mkeilman made the change

**Comment by mkeilman** [comment] 2022-06-09 20:26
> @mkeilman made the change

Thanks, I think that will do it!

**Comment by gurhar1133** [comment] 2022-06-09 23:18
@robnagler I added `group_prefix` explanation to the `case_dirs` section. LMK your thoughts

https://github.com/radiasoft/pykern/wiki/Testing

**Comment by robnagler** [comment] 2022-06-10 23:58
I added a branch rjn-testing where I wrote a bit more of a tutorial like intro. I'd like to see more of a conversational style with a flow like this. LMK what you think.

**Comment by gurhar1133** [comment] 2022-06-13 17:57
Noticed a couple things:

1) in the first example in the introduction, I think:
```python
pkunit.pkeq('hello world, pkexample.echo(prefix='hello ', suffix='world'))
```
was intended to be:
```python
pkunit.pkeq('hello world', pkexample.echo(prefix='hello ', suffix='world'))
```
just a missing `'` I think

2) `It's always good to have a docstring so that's first. ` not sure what's meant by "so that's first". But that might not be a mistake and might just be my confusion.

**Comment by robnagler** [comment] 2022-06-13 18:39
Feel free to edit :)

**Comment by gurhar1133** [comment] 2022-06-13 18:54
Ok. I still don't understand 2. though.

**Comment by robnagler** [comment] 2022-06-13 20:17
doctstring is first thing in the module.

**Comment by gurhar1133** [comment] 2022-06-14 15:57
Merged and pushed

**Comment by gurhar1133** [comment] 2022-06-15 17:09
More to be done here? or is this one closed?

**Comment by robnagler** [comment] 2022-06-16 00:06
@mkeilman What do you think?

**Comment by mkeilman** [comment] 2022-06-20 18:52
> @mkeilman What do you think?

Well I made a few edits for style, grammar, and I hope clarity. Feel free to quibble or correct.

**Comment by robnagler** [comment] 2022-06-21 00:39
Can we close the issue?

**Comment by mkeilman** [comment] 2022-06-21 00:48
Yes, I will do that.

**Closed by mkeilman** 2022-06-21 00:48 UTC
